### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by Matthieu-BRANTHOME** [mosh98/Ordinal_Classifier#1]
How to use this package?

pip install ordinal-classification doesn't work.

Thanks in advance,

**Comment by mosh98** [comment]
hey man, 
i will try to fix it over the weekend so you can easily use this.

Best,

**Comment by Matthieu-BRANTHOME** [comment]
Thks a lot!

I look forward to using it!

**Comment by Matthieu-BRANTHOME** [comment]
Any new about your package ?

**Comment by mosh98** [comment]
Hi, here is an example on how to import this package.

https://colab.research.google.com/drive/1CkoeHze9ee2WFe7P0sgqZS4Wyx9_rD8b?usp=sharing

Hope it helps

**Comment by Matthieu-BRANTHOME** [comment]
Thks a lot!

Is your package compatible with Pipeline and cross validation?

**Comment by mosh98** [comment]
it should :)
