### ISSUE TITLE
I Cann't use `predict()` or `coef` with OC classifier

### ISSUE THREAD

**Issue by guilhermeparreira** [mosh98/Ordinal_Classifier#2]
Hi there! Thanks for the package!

I tried to run your example, but the `predict` command raised an error (as well `uniques_class`, as shown in here:

![image](https://user-images.githubusercontent.com/13880005/199730608-46bb292c-476f-4281-b3ee-0b244cf3c6ed.png)

--------------------------------------------------------------------------------------------------------------------------

Also, when I tried to get the `coefficients` or `feature_importances_` it gave to me no results:
![image](https://user-images.githubusercontent.com/13880005/199731075-932aeadc-359b-43c6-8dbe-02232b18b9c2.png)

Do you have some idea on how can I handle these issues? (Or any other strategy?)

Thanks in advance!!

**Comment by mosh98** [comment]
weird, getting the same problem too, i'll look into it

**Comment by sarim-zafar** [comment]
Any update on this?

**Comment by mosh98** [comment]
soryy guys been quite busy, i'll look into it. Ofcourse feel free to make any pull request

**Comment by mosh98** [comment]
the package works now. enjoy!
