### ISSUE TITLE
self.uniques_class[1]

### ISSUE THREAD

**Issue by christopher-schroeder** [mosh98/Ordinal_Classifier#3]
Hey,
I might be wrong here but shouldn't it be

binary_y = (y > self.uniques_class[**i**]).astype(np.uint8)

instead of

binary_y = (y > self.uniques_class[**1**]).astype(np.uint8)

? Best
Christo

**Comment by mosh98** [comment]
could be i'll check it out

**Comment by mosh98** [comment]
thanks fo that. The package now works
